[project]
name = "back-to-future"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mishalo4ka", email = "omvgim6@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "argparse>=1.4.0",
    "json",
]

[project.scripts]
back-to-future = "back_to_future:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
